{{- if .Values.networkChangeHook.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "groundlight-edge-endpoint.fullname" . }}-install-network-hook
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "groundlight-edge-endpoint.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    spec:
      serviceAccountName: {{ include "groundlight-edge-endpoint.serviceAccountName" . }}-k3s-config
      hostNetwork: true
      hostPID: true
      containers:
      - name: install-network-hook
        image: alpine:latest
        command:
        - chroot
        - /host
        - /bin/bash
        - -c
        - |
          {{- tpl (.Files.Get "files/install-network-hook.sh") . | nindent 10 }}
        securityContext:
          privileged: true
        volumeMounts:
        - name: host-root
          mountPath: /host
      volumes:
      - name: host-root
        hostPath:
          path: /
      restartPolicy: OnFailure
      nodeSelector:
        node-role.kubernetes.io/control-plane: "true"

{{- end }}


