[project]
name = "load-testing"
version = "0.1.0"
description = "Scripts of testing the performance of a Grounlight Edge Endpoint"
requires-python = ">=3.13"
dependencies = [
    "gputil>=1.4.0",
    "groundlight>=0.23.2",
    "matplotlib>=3.10.6",
    "opencv-python>=4.12.0.88",
    "psutil>=7.1.0",
    "pydantic>=2.11.9",
    "tqdm>=4.67.1",
]
